# Generated by Django 5.1.7 on 2025-05-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='openingday',
            field=models.CharField(blank='True', max_length=15),
        ),
    ]
