# Generated by Django 5.1.7 on 2025-05-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_touristspot_openingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='openingday',
            field=models.CharField(blank='True', choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
    ]
