# Generated by Django 5.1.7 on 2025-05-07 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_touristspot_openingday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='status',
        ),
    ]
