# Generated by Django 5.1.7 on 2025-05-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_touristspot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spots'),
        ),
    ]
