# Generated by Django 5.1.7 on 2025-05-08 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_touristspot_openingday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('review', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.touristspot')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
