# Generated by Django 5.1.7 on 2025-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photogallery',
            old_name='type',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='caption',
            field=models.TextField(default='Lorem ipsum dolor, sit amet consectetur adipisicing elit.'),
        ),
    ]
