# Generated by Django 5.1.7 on 2025-05-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_rename_type_photogallery_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='status',
        ),
    ]
