# Generated by Django 5.1.7 on 2025-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_customuser_image_alter_photogallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 'Bad'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Good'), ('5', 'Excellent')], default='1', max_length=10),
        ),
    ]
