# Generated by Django 5.1.7 on 2025-05-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='spotID',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userID',
            new_name='user',
        ),
    ]
