# Generated by Django 5.1.7 on 2025-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_rename_spotid_review_spot_rename_userid_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='openingday',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=50),
        ),
    ]
