# Generated by Django 5.1.7 on 2025-05-09 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_touristspot_openingday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingline',
            name='visitDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
