# Generated by Django 5.1.7 on 2025-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_alter_booking_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='totalcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
