# Generated by Django 5.1.7 on 2025-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_booking_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='entrancefee',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
