# Generated by Django 5.1.7 on 2025-05-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_payment_booking_alter_payment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NP', 'Not Paid'), ('P', 'Pending'), ('S', 'Success'), ('F', 'Failed'), ('C', 'Cancelled'), ('R', 'Refunded')], default='P', max_length=2),
        ),
    ]
